import parasite from './parasite.png'
import bruteforce from './bruteforce.jpg'
import crisscross from './crisscross.jpg'
import entourage from './entourage.jpg'
import birdsofprey from './birdsofprey.jpg'
import whiteheat from './whiteheat.jpg'
import mildredpierce from './mildredpierce.jpg'
import thetreasureofthesierramadre from './thetreasureofthesierramadre.jpg'
import outofthepast from './outofthepast.jpg'
import doubleindemnity from './doubleindemnity.jpg'
import gilda from './gilda.jpg'
import sunsetboulevard from './sunsetboulevard.jpg'
import thebigheat from './thebigheat.jpg'
import theasphaltjungle from './theasphaltjungle.jpg'
import thekilling from './thekilling.jpg'

export default { parasite, bruteforce, crisscross, entourage, birdsofprey, whiteheat, mildredpierce, thetreasureofthesierramadre, outofthepast, doubleindemnity, gilda, sunsetboulevard, thebigheat, theasphaltjungle, thekilling }