import parasite from '../movies/parasite.png'
import bruteforce from '../movies/bruteforce.jpg'
import crisscross from '../movies/crisscross.jpg'
import entourage from '../movies/entourage.jpg'
import birdsofprey from '../movies/birdsofprey.jpg'
import whiteheat from '../movies/whiteheat.jpg'
import mildredpierce from '../movies/mildredpierce.jpg'
import thetreasureofthesierramadre from '../movies/thetreasureofthesierramadre.jpg'
import outofthepast from '../movies/outofthepast.jpg'
import doubleindemnity from '../movies/doubleindemnity.jpg'
import gilda from '../movies/gilda.jpg'
import sunsetboulevard from '../movies/sunsetboulevard.jpg'
import thebigheat from '../movies/thebigheat.jpg'

export default { parasite, bruteforce, crisscross, entourage, birdsofprey, whiteheat, mildredpierce, thetreasureofthesierramadre, outofthepast, doubleindemnity, gilda, sunsetboulevard, thebigheat }