import nhl94 from './nhl94.jpg'
import warcraft3reforged from './warcraft3reforged.png'
import newsupermariobrosudeluxe from './newsupermariobrosudeluxe.jpg'
import supermarioworld from './supermarioworld.png'
import breathoffireii from './breathoffireii.jpg'
import baldursgate from './baldursgate.png'
import baldursgatesiegeofdragonspear from './baldursgatesiegeofdragonspear.png'
import baldursgateiienhancededition from './baldursgateiienhancededition.jpg'
import supermario64 from './supermario64.jpg'
import diddykongracing from './diddykongracing.jpg'
import sonicthehedgehog2 from './sonicthehedgehog2.jpg'
import drrobotniksmeanbeanmachine from './drrobotniksmeanbeanmachine.jpg'
import sonicthehedgehog3 from './sonicthehedgehog3.jpg'
import sonicmania from './sonicmania.jpg'
import supermariobros3 from './supermariobros3.png'
import mariokart8deluxe from './mariokart8deluxe.png'
import starcraft from './starcraft.jpeg'

export default { starcraft, nhl94, warcraft3reforged, newsupermariobrosudeluxe, supermarioworld, breathoffireii, baldursgate, baldursgatesiegeofdragonspear, baldursgateiienhancededition, supermario64, diddykongracing, sonicthehedgehog2, drrobotniksmeanbeanmachine, sonicthehedgehog3, sonicmania, supermariobros3, mariokart8deluxe }