import bandofgypsys from './bandofgypsys.jpg'
import sgtpeppers from './sgtpeppers.jpg'
import shocktroops from './shocktroops.jpg'
import theinterrupters from './theinterrupters.jpg'
import thirteensongs from './thirteensongs.png'
import apostrophe from './apostrophe.jpg'
import brownalbum from './brownalbum.jpg'
import foxtrot from './foxtrot.jpg'
import larkstongues from './larkstongues.jpg'
import qarewenotmenawearedevo from './qarewenotmenawearedevo.jpg'
import freedomofchoice from './freedomofchoice.jpg'
import pointofknowreturn from './pointofknowreturn.jpg'
import minimummaximum from './minimummaximum.png'
import thegrandwazoo from './thegrandwazoo.jpg'
import enemaofthestate from './enemaofthestate.jpg'
import licensedtoill from './licensedtoill.jpg'
import letthedominoesfall from './letthedominoesfall.jpg'
import exileonmainst from './exileonmainst.jpg'
import rageagainstthemachine from './rageagainstthemachine.jpg'
import strictlybusiness from './strictlybusiness.jpg'
import paulsboutique from './paulsboutique.jpg'
import somethingforeverybody from './somethingforeverybody.jpeg'
import beggarsbanquet from './beggarsbanquet.jpg'
import rubbersoul from './rubbersoul.jpg'

export default { bandofgypsys, sgtpeppers, thirteensongs, shocktroops, theinterrupters, apostrophe, brownalbum, foxtrot, larkstongues, qarewenotmenawearedevo, freedomofchoice, pointofknowreturn, minimummaximum, thegrandwazoo, enemaofthestate, licensedtoill, letthedominoesfall, exileonmainst, rageagainstthemachine, strictlybusiness, paulsboutique, somethingforeverybody, beggarsbanquet, rubbersoul }
