import entourage5 from './entourage5.jpg'
import entourage6 from './entourage6.jpg'
import entourage7 from './entourage7.jpeg'
import entourage8 from './entourage8.jpg'
import flightoftheconchords1 from './flightoftheconchords1.jpg'
import flightoftheconchords2 from './flightoftheconchords2.jpg'
import agentcarter1 from './agentcarter1.jpg'
import dragonballzkai1 from './dragonballzkai1.jpg'
import dragonballsuper1 from './dragonballsuper1.jpg'
import dragonballzkai2 from './dragonballzkai2.jpg'
import dragonballzkai3 from './dragonballzkai3.jpg'
import shaqlife from './shaqlife.jpg'
import themandalorian1 from './themandalorian1.jpg'
import whoselineisitanywayaisha from './whoselineisitanywayaisha.jpg'
import thebestofwhoselineisitanyway from './thebestofwhoselineisitanyway.jpg'

export default { entourage5, entourage6, entourage7, entourage8, flightoftheconchords1, flightoftheconchords2, agentcarter1, dragonballzkai1, dragonballsuper1, dragonballzkai2, dragonballzkai3, shaqlife, themandalorian1, whoselineisitanywayaisha, thebestofwhoselineisitanyway }